
android.useAndroidX=true
android.enableJetifier=true
# Enable Gradle daemon for faster builds
org.gradle.daemon=true
# Enable parallel execution
org.gradle.parallel=true
# Enable configuration on demand
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
# Enable Gradle build cache
org.gradle.caching=true
 